/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRequiredRouteImport } from './routes/demo.required'
import { Route as DemoExpiredRouteImport } from './routes/demo.expired'
import { Route as DemoTokenRouteImport } from './routes/demo.$token'
import { Route as AdminDemoRouteImport } from './routes/admin.demo'
import { Route as ApiDemoTokensRouteImport } from './routes/api.demo.tokens'
import { Route as ApiDemoNavHintRouteImport } from './routes/api.demo.nav-hint'
import { Route as ApiDemoClosingRouteImport } from './routes/api.demo.closing'
import { Route as ApiDemoSessionTokenRouteImport } from './routes/api.demo.session.$token'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRequiredRoute = DemoRequiredRouteImport.update({
  id: '/demo/required',
  path: '/demo/required',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoExpiredRoute = DemoExpiredRouteImport.update({
  id: '/demo/expired',
  path: '/demo/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTokenRoute = DemoTokenRouteImport.update({
  id: '/demo/$token',
  path: '/demo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/admin/demo',
  path: '/admin/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoTokensRoute = ApiDemoTokensRouteImport.update({
  id: '/api/demo/tokens',
  path: '/api/demo/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNavHintRoute = ApiDemoNavHintRouteImport.update({
  id: '/api/demo/nav-hint',
  path: '/api/demo/nav-hint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoClosingRoute = ApiDemoClosingRouteImport.update({
  id: '/api/demo/closing',
  path: '/api/demo/closing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoSessionTokenRoute = ApiDemoSessionTokenRouteImport.update({
  id: '/api/demo/session/$token',
  path: '/api/demo/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/demo': typeof AdminDemoRoute
  '/demo/$token': typeof DemoTokenRoute
  '/demo/expired': typeof DemoExpiredRoute
  '/demo/required': typeof DemoRequiredRoute
  '/api/demo/closing': typeof ApiDemoClosingRoute
  '/api/demo/nav-hint': typeof ApiDemoNavHintRoute
  '/api/demo/tokens': typeof ApiDemoTokensRoute
  '/api/demo/session/$token': typeof ApiDemoSessionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/demo': typeof AdminDemoRoute
  '/demo/$token': typeof DemoTokenRoute
  '/demo/expired': typeof DemoExpiredRoute
  '/demo/required': typeof DemoRequiredRoute
  '/api/demo/closing': typeof ApiDemoClosingRoute
  '/api/demo/nav-hint': typeof ApiDemoNavHintRoute
  '/api/demo/tokens': typeof ApiDemoTokensRoute
  '/api/demo/session/$token': typeof ApiDemoSessionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/demo': typeof AdminDemoRoute
  '/demo/$token': typeof DemoTokenRoute
  '/demo/expired': typeof DemoExpiredRoute
  '/demo/required': typeof DemoRequiredRoute
  '/api/demo/closing': typeof ApiDemoClosingRoute
  '/api/demo/nav-hint': typeof ApiDemoNavHintRoute
  '/api/demo/tokens': typeof ApiDemoTokensRoute
  '/api/demo/session/$token': typeof ApiDemoSessionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/avis'
    | '/contact'
    | '/services'
    | '/admin/demo'
    | '/demo/$token'
    | '/demo/expired'
    | '/demo/required'
    | '/api/demo/closing'
    | '/api/demo/nav-hint'
    | '/api/demo/tokens'
    | '/api/demo/session/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/avis'
    | '/contact'
    | '/services'
    | '/admin/demo'
    | '/demo/$token'
    | '/demo/expired'
    | '/demo/required'
    | '/api/demo/closing'
    | '/api/demo/nav-hint'
    | '/api/demo/tokens'
    | '/api/demo/session/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/avis'
    | '/contact'
    | '/services'
    | '/admin/demo'
    | '/demo/$token'
    | '/demo/expired'
    | '/demo/required'
    | '/api/demo/closing'
    | '/api/demo/nav-hint'
    | '/api/demo/tokens'
    | '/api/demo/session/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AvisRoute: typeof AvisRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  AdminDemoRoute: typeof AdminDemoRoute
  DemoTokenRoute: typeof DemoTokenRoute
  DemoExpiredRoute: typeof DemoExpiredRoute
  DemoRequiredRoute: typeof DemoRequiredRoute
  ApiDemoClosingRoute: typeof ApiDemoClosingRoute
  ApiDemoNavHintRoute: typeof ApiDemoNavHintRoute
  ApiDemoTokensRoute: typeof ApiDemoTokensRoute
  ApiDemoSessionTokenRoute: typeof ApiDemoSessionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/required': {
      id: '/demo/required'
      path: '/demo/required'
      fullPath: '/demo/required'
      preLoaderRoute: typeof DemoRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/expired': {
      id: '/demo/expired'
      path: '/demo/expired'
      fullPath: '/demo/expired'
      preLoaderRoute: typeof DemoExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$token': {
      id: '/demo/$token'
      path: '/demo/$token'
      fullPath: '/demo/$token'
      preLoaderRoute: typeof DemoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demo': {
      id: '/admin/demo'
      path: '/admin/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/tokens': {
      id: '/api/demo/tokens'
      path: '/api/demo/tokens'
      fullPath: '/api/demo/tokens'
      preLoaderRoute: typeof ApiDemoTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/nav-hint': {
      id: '/api/demo/nav-hint'
      path: '/api/demo/nav-hint'
      fullPath: '/api/demo/nav-hint'
      preLoaderRoute: typeof ApiDemoNavHintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/closing': {
      id: '/api/demo/closing'
      path: '/api/demo/closing'
      fullPath: '/api/demo/closing'
      preLoaderRoute: typeof ApiDemoClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/session/$token': {
      id: '/api/demo/session/$token'
      path: '/api/demo/session/$token'
      fullPath: '/api/demo/session/$token'
      preLoaderRoute: typeof ApiDemoSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AvisRoute: AvisRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  AdminDemoRoute: AdminDemoRoute,
  DemoTokenRoute: DemoTokenRoute,
  DemoExpiredRoute: DemoExpiredRoute,
  DemoRequiredRoute: DemoRequiredRoute,
  ApiDemoClosingRoute: ApiDemoClosingRoute,
  ApiDemoNavHintRoute: ApiDemoNavHintRoute,
  ApiDemoTokensRoute: ApiDemoTokensRoute,
  ApiDemoSessionTokenRoute: ApiDemoSessionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
